mysql:
  username: ${DATABASE_MYSQL_USERNAME}
  password: ${DATABASE_MYSQL_PASSWORD}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none